--Thanks IIEERRAA for fluid furnaces textures
require("prototypes.item.item")
require("prototypes.recipe.recipe")
--require("prototypes.recipe.smelting")
--require("prototypes.recipe.casting")
require("prototypes.tile.tile")
--require("prototypes.entity.entity")
--require("prototypes.category.recipe-category")
--require("prototypes.fluid.fluid")
--require("prototypes.item.item-group")